"""add custom fields tables

Revision ID: 4bb5ba31dcf2
Revises: 1ff23e3ab88b
Create Date: 2026-06-10 20:28:11.448636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb5ba31dcf2'
down_revision = '1ff23e3ab88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'EMAIL', 'BOOLEAN', name='fieldtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('field_id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_field_name')
    )
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_project_id'), ['project_id'], unique=False)

    op.create_table('custom_field_values',
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['custom_field_definitions.field_id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['devices.instance_id'], ),
    sa.PrimaryKeyConstraint('value_id'),
    sa.UniqueConstraint('instance_id', 'field_id', name='uq_device_field_value')
    )
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_values_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_value'), ['value'], unique=False)
        batch_op.create_index('ix_custom_field_values_field_id_value',['field_id', 'value'],unique=False
)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.drop_index('ix_custom_field_values_field_id_value')
        batch_op.drop_index(batch_op.f('ix_custom_field_values_value'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_instance_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_field_id'))

    op.drop_table('custom_field_values')

    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_project_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_name'))

    op.drop_table('custom_field_definitions')